### ISSUE TITLE
500 Error from NOMADS

### ISSUE THREAD

**Issue by Craytor** [CoDNEXLAB/grads#3]
Hello there!

To start off, I think this is an amzing source for grads files! I'm extremly excited to start navigating and learing more!

I've got a version set up for the most part on one of my development servers. When I go to run any of the ```kickers``` in ```/grads/kickers```, I'm presented with a 500 error from NOMADS.

In the terminal, this is the file that the ```cfskicker.csh``` is trying to grab:
`http://nomads.ncep.noaa.gov/cgi-bin/filter_cfs_pgb.pl?file=pgbf2017022100.01.20161129.grb2&lev_3000-0_m_above_ground=on&lev_500_mb=on&lev_850_mb=on&lev_mean_sea_level=on&lev_surface=on&var_CAPE=on&var_HGT=on&var_HLCY=on&var_PRMSL=on&var_TMP=on&var_UGRD=on&var_VGRD=on&var_CIN=on&var_HGT=on&lev_2_m_above_ground=on&leftlon=0&rightlon=360&toplat=90&bottomlat=-90&dir=%2Fcfs.20161129%2F%2F6hrly_grib_01`

Also, is this how I should begin to use this project? For example, I run the kicker (to get grib data), and then I run the runner scripts (to create images like [http://atlas.cod.edu/data/forecast/HRRR/22/MA/HRRRMA_prec_radar_000.png](http://atlas.cod.edu/data/forecast/HRRR/22/MA/HRRRMA_prec_radar_000.png)? I feel that a little bit more information in the ```Read Me``` like possibly a getting started area may be helpful.

Any suggestions?

Thanks for your time, and an awesome project!

**Comment by vgensini** [comment]
Hi Craytor, 

Thanks for commenting and opening an issue.  I will try to work on getting some more information in the README. You are getting a 500 error from NOMADS because it doesn't appear that you are passing the ***kicker.csh script any arguments.  We use the kicker scripts (passing the run hour; 00, 06, 12, 18) to go grab the data from NOMADS. At this point, there is no plans to make this more dynamic, since this particular project is designed to work with our current configuration of servers where we get a lot of data via LDM over the SBN NOAAPort feed. 

Best,
